export default {
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    { name: 'header', title: 'Header', default: true },
    { name: 'footer', title: 'Footer' },
  ],
  fields: [
    {
      name: 'profileImage',
      title: 'Profile image',
      type: 'image',
      group: 'header',
      options: { hotspot: true },
    },
    {
      name: 'greeting',
      title: 'Greeting',
      type: 'string',
      group: 'header',
      description: 'e.g. Hello, I am',
    },
    {
      name: 'name',
      title: 'Name',
      type: 'string',
      group: 'header',
      description: 'e.g. Isaac',
    },
    {
      name: 'roles',
      title: 'Role tags',
      type: 'array',
      group: 'header',
      of: [{ type: 'string' }],
      description: 'Shown as tags under your name',
    },
    {
      name: 'contactEmail',
      title: 'Contact email',
      type: 'string',
      group: 'footer',
      validation: (Rule) => Rule.email(),
    },
    {
      name: 'contactPhone',
      title: 'Contact phone (display)',
      type: 'string',
      group: 'footer',
      description: 'Shown in the footer, e.g. +234 906-7322344',
    },
    {
      name: 'contactPhoneTel',
      title: 'Contact phone (tel link)',
      type: 'string',
      group: 'footer',
      description: 'Optional. Used in tel: link. Leave empty to derive from display phone.',
    },
    {
      name: 'copyrightLine1',
      title: 'Copyright line 1',
      type: 'string',
      group: 'footer',
      description: 'e.g. @2026 ISAAC TARIBI',
    },
    {
      name: 'copyrightLine2',
      title: 'Copyright line 2',
      type: 'string',
      group: 'footer',
      description: 'e.g. All rights reserved',
    },
  ],
}
